name: publish 
on:
  push:
    branches: 
      - main
  workflow_dispatch:
  # TODO: add scheduled publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: python3 maker.py --api-key={{ secrets.SEAFILE_API_KEY }}
      - run: cd output && mkdocs gh-deploy --force
