name: publish 
on:
  push:
    branches: 
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - templates/latex/*
      - scripts/report_issues.py
      - scripts/archive_site.py
      - resources/latex/*
      - feiyue/frontend/latex.py
      - .github/workflows/*
      - '!.github/workflows/publish.yml'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: python3 maker.py --frontend=mkdocs --api-key=${{ secrets.SEAFILE_API_KEY }}
      - run: cd output && mkdocs gh-deploy --force

      - run: bash scripts/export.sh
        env:
          SEAFILE_ACCOUNT_TOKEN: ${{ secrets.SEAFILE_ACCOUNT_TOKEN }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: |
            feiyue.dtable
            .cache/*
