name: report-issues 
on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip3 install requests
      - id: report
        run: python3 scripts/report_issues.py --api-key=${{ secrets.SEAFILE_API_KEY }}
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "output/issues.log"
      - id: cat
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          {
            echo 'ISSUES<<EOF'
            cat output/issues.log
            echo EOF
          } >> "$GITHUB_ENV"
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Issues found in the database
          body: ${{ env.ISSUES }}
